logging:
  #日志存储地址
  file: "logs/app-client.log"
info:
  name : "App 后端接口"

server:
  #端口号
  port: 8888
  context-path: /
  address: client1.com
  
spring:
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
 
 
